# Generated by Django 4.1.1 on 2022-09-14 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_name', models.CharField(max_length=10)),
                ('upload_image', models.ImageField(upload_to='media/')),
                ('description', models.CharField(max_length=1000)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
